# Makefile.deps created Thu Apr 27 21:57:01 PDT 2017 by /Library/Developer/CommandLineTools/usr/bin/make
main.o: main.cpp auxlib.h string_set.h cppstrtok.h
auxlib.o: auxlib.cpp auxlib.h
string_set.o: string_set.cpp string_set.h
cppstrtok.o: cppstrtok.cpp cppstrtok.h string_set.h
